# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Make build script executable
      run: chmod +x build.sh

    - name: Build binaries using Docker
      run: ./build.sh

    - name: Run Go tests
      run: go test -v ./...

