name: Go Build and Test with LLVM 17

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install LLVM 17
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-17 lld-17 llvm-17-dev build-essential libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev xorg-dev
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-17 100
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-17 100
        

    - name: Check clang in PATH
      run: |
        which clang
        clang --version


    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    - name: Make build script executable
      run: chmod +x build_gh.sh

    - name: Build with LLVM 17
      env:
        CC: clang
        CXX: clang++
        CGO_ENABLED: 1
      run: ./build_gh.sh

    - name: Run Go tests
      run: go test -v ./...
