name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install zip
      run: sudo apt-get install zip -y

    - name: Make build script executable
      run: chmod +x build_gh.sh

    - name: Extract tag version
      id: extract_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

    - name: Build
      run: ./build_gh.sh

    - name: Archive builds
      run: |
        mkdir dist
        for f in build/*; do
          base=$(basename "$f")
          zip "dist/${base}-${VERSION}.zip" "$f"
        done

    - name: Create GitHub Release with Changelog
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ env.VERSION }}
        tag_name: ${{ env.VERSION }}
        generate_release_notes: true
        files: dist/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
